# Registry type according to https://github.com/open-data/ckanext-canada

ckan.plugins = canada_theme activity validation canada_forms canada_internal canada_public recombinant datastore dsaudit canada_datasets scheming_organizations fluent cloudstorage canada_security xloader datatables_view image_view text_view webpage_view openapi_view power_bi_view gcnotify
