# Portal setup according to https://github.com/open-data/ckanext-canada

ckan.plugins = envvars canada_theme activity dcat dcat_json_interface canada_forms canada_public canada_datasets scheming_organizations fluent recombinant cloudstorage canada_security datastore text_view image_view datatables_view webpage_view openapi_view power_bi_view
